version: '3.1'

services:
  web:
    build: 
      context:  ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: go_user
      DB_PASSWORD: go_pwd
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: tododb
      SERVER_PORT: 8080
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: go
      MYSQL_DATABASE: tododb
      MYSQL_USER: go_user
      MYSQL_PASSWORD: go_pwd
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/1.sql"

volumes:
  dbdata:
